name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      # TODO(wcalixto): add a build step here
      - name: Start the instance
        run: deno run --allow-read --allow-net mod.ts

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "deno-one"
          entrypoint: "./main.ts" # TODO(wcalixto): update